### ISSUE TITLE
glyph placeholders / non-rendering text in demos

### ISSUE THREAD

**Issue by graydon** [servo/pathfinder#412] opened 2020-07-22 19:44 UTC
Ubuntu 18.04 LTS, fairly stock environment, I checked out pathfinder and did `cd examples/canvas_nanovg/` then `cargo run --release` and I got the following display with missing glyph placeholders:

![image](https://user-images.githubusercontent.com/14097/88220742-3e04ba00-cc18-11ea-9d04-8da248f3cf87.png)

Since I have no idea what the cause is -- looks like the fonts are in the tree even! -- I'll just list everything else about the software & hardware context:

Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz

4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]

X.Org version: 1.19.6

~~~

$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/graydon/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-07-18-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.44.0-nightly (14061868b 2020-04-10)

$ nvidia-smi 
Wed Jul 22 12:39:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:05:00.0  On |                  N/A |
| 31%   38C    P0    N/A /  75W |   2168MiB /  4038MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
~~~

**Comment by s3bk** [comment] 2020-07-22 19:47
duplicate of https://github.com/servo/pathfinder/issues/194

**Comment by jdm** [comment] 2020-07-22 19:52
Ultimately there is a PR to address this in https://github.com/linebender/skribo/pull/35 with some discussion about an alternative fix. This occurs when the system harfbuzz libraries are older than 2.0, iirc.

**Closed** 2020-07-22 19:51 UTC
